backend:
  name: git-gateway
  branch: main  # Sau branch-ul pe care vrei să administrezi conținutul

media_library:
  name: uploadcare  # Poți folosi și "cloudinary" pentru CDN
  config:
    publicKey: demo  # Înlocuiește cu cheia ta

collections:
  - name: "portfolio"
    label: "Portfolio"
    folder: "content/portfolio"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Country", name: "country", widget: "select", options: ["romania", "germany", "netherlands"] }
      - { label: "Images", name: "images", widget: "list", field: { label: "Image", name: "image", widget: "image" } }
